# Generated by Django 5.2.17 on 2026-09-11 03:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role_custom_data_team_custom_data_user_custom_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('symbol', models.CharField(blank=True, default='', max_length=8)),
                ('rate', models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['code'],
            },
        ),
    ]
