# Generated by Django 5.2.17 on 2026-09-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_webhook_webhookqueueitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('event', models.CharField(choices=[('before_save', 'Before Save'), ('after_save', 'After Save')], max_length=20)),
                ('script', models.TextField(help_text="One statement per line, e.g. `probability = 50` or `notify('Deal updated')`.")),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'formulas',
                'ordering': ['entity_type', 'event', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('event', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('condition', models.TextField(blank=True, default='', help_text="Optional expression, e.g. `stage == 'Closed Won'`.")),
                ('actions', models.JSONField(blank=True, default=list, help_text='List of actions, e.g. [{"type": "set_field", "field": "priority", "value": "High"}].')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['entity_type', 'event', 'order', 'id'],
            },
        ),
    ]
