# Generated by Django 5.2.17 on 2026-09-11 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_formula_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='CamelCase, e.g. Project. Used in URLs and metadata.', max_length=64, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('label_plural', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'custom entities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DynamicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('teams', models.ManyToManyField(blank=True, related_name='+', to='core.team')),
            ],
            options={
                'verbose_name': 'Custom record',
                'verbose_name_plural': 'Custom records',
                'ordering': ['-created_at'],
            },
        ),
    ]
