# Generated by Django 5.2.17 on 2026-09-11 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0008_userreaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('body_plain', models.TextField(blank=True, default='')),
                ('is_html', models.BooleanField(default=False)),
                ('from_address', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('to_address', models.TextField(blank=True, default='')),
                ('cc_address', models.TextField(blank=True, default='')),
                ('bcc_address', models.TextField(blank=True, default='')),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sending', 'Sending'), ('Sent', 'Sent'), ('Archived', 'Archived'), ('Failed', 'Failed')], default='Archived', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('parent_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('teams', models.ManyToManyField(blank=True, related_name='+', to='core.team')),
            ],
            options={
                'verbose_name': 'Email',
                'ordering': ['-date_sent', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email_address', models.EmailField(blank=True, default='', max_length=254)),
                ('imap_host', models.CharField(max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_ssl', models.BooleanField(default=True)),
                ('imap_username', models.CharField(blank=True, default='', max_length=255)),
                ('imap_password', models.CharField(blank=True, default='', max_length=255)),
                ('folder', models.CharField(blank=True, default='INBOX', max_length=255)),
                ('unseen_only', models.BooleanField(default=True, help_text='Fetch only unread messages.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('default_assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Account',
                'verbose_name_plural': 'Email Accounts',
                'ordering': ['name'],
            },
        ),
    ]
