# Generated by Django 5.2.17 on 2026-09-11 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_savedfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='folder',
            field=models.CharField(blank=True, default='', help_text='IMAP folder it came from.', max_length=255),
        ),
        migrations.AddField(
            model_name='email',
            name='parent_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core.email'),
        ),
        migrations.AddField(
            model_name='email',
            name='thread_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='folder',
            field=models.CharField(blank=True, default='INBOX', help_text='Comma-separated IMAP folders to poll.', max_length=255),
        ),
    ]
