# Generated by Django 5.2.17 on 2026-09-11 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_email_folder_email_parent_email_email_thread_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.currency')),
            ],
            options={
                'ordering': ['-date', 'currency__code'],
                'indexes': [models.Index(fields=['currency', '-date'], name='core_curren_currenc_f5169d_idx')],
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
