# Generated by Django 5.2.17 on 2026-09-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_currencyrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customentity',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Optional HEX color.', max_length=16),
        ),
        migrations.AddField(
            model_name='customentity',
            name='duplicate_check_fields',
            field=models.CharField(blank=True, default='', help_text='Comma-separated base fields compared for duplicates (name).', max_length=255),
        ),
        migrations.AddField(
            model_name='customentity',
            name='icon',
            field=models.CharField(blank=True, default='extension', help_text='Material Symbols icon name.', max_length=64),
        ),
        migrations.AddField(
            model_name='customentity',
            name='menu_order',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='customentity',
            name='search_fields',
            field=models.CharField(blank=True, default='name', help_text='Comma-separated base fields used by search (name).', max_length=255),
        ),
        migrations.AddField(
            model_name='customentity',
            name='show_in_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customentity',
            name='sort_direction',
            field=models.CharField(choices=[('asc', 'Ascending'), ('desc', 'Descending')], default='desc', max_length=4),
        ),
        migrations.AddField(
            model_name='customentity',
            name='sort_field',
            field=models.CharField(choices=[('created_at', 'Created At'), ('modified_at', 'Modified At'), ('name', 'Name')], default='created_at', max_length=20),
        ),
        migrations.AddField(
            model_name='customentity',
            name='stream',
            field=models.BooleanField(default=True),
        ),
    ]
