# Generated by Django 5.2.17 on 2026-09-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customentity_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlink',
            name='foreign_name',
            field=models.CharField(blank=True, default='', help_text='Reverse link name.', max_length=64),
        ),
        migrations.AddField(
            model_name='customlink',
            name='label_foreign',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='customlink',
            name='name',
            field=models.CharField(help_text='snake_case link name on this entity.', max_length=64),
        ),
        migrations.CreateModel(
            name='RecordLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(db_index=True, max_length=64)),
                ('source_id', models.PositiveBigIntegerField()),
                ('link', models.CharField(db_index=True, max_length=64)),
                ('target_type', models.CharField(db_index=True, max_length=64)),
                ('target_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['pk'],
                'indexes': [models.Index(fields=['source_type', 'source_id', 'link'], name='core_record_source__b71519_idx'), models.Index(fields=['target_type', 'target_id', 'link'], name='core_record_target__5e22f9_idx')],
                'unique_together': {('source_type', 'source_id', 'link', 'target_type', 'target_id')},
            },
        ),
    ]
