# Generated by Django 5.2.17 on 2026-09-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_customlink_foreign_name_customlink_label_foreign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('varchar', 'Varchar'), ('text', 'Text'), ('enum', 'Enum'), ('multiEnum', 'Multi enum'), ('bool', 'Bool'), ('int', 'Int'), ('float', 'Float'), ('decimal', 'Decimal'), ('number', 'Number (auto)'), ('date', 'Date'), ('datetime', 'Datetime'), ('email', 'Email'), ('phone', 'Phone'), ('url', 'URL'), ('currency', 'Currency'), ('address', 'Address'), ('file', 'File'), ('image', 'Image'), ('attachmentMultiple', 'Attachments'), ('foreign', 'Foreign')], max_length=20),
        ),
        migrations.CreateModel(
            name='NextNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=64)),
                ('field_name', models.CharField(max_length=64)),
                ('value', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'unique_together': {('entity_type', 'field_name')},
            },
        ),
    ]
