# Generated by Django 5.2.17 on 2026-09-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_customfield_field_type_nextnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='customentity',
            name='show_in_calendar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customentity',
            name='template',
            field=models.CharField(choices=[('base', 'Base'), ('person', 'Person'), ('company', 'Company'), ('event', 'Event')], default='base', help_text='Initial fields and layouts; locked after creation.', max_length=20),
        ),
    ]
