# Generated by Django 5.2.17 on 2026-09-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_customentity_show_in_calendar_customentity_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='customentity',
            name='status_field',
            field=models.CharField(blank=True, default='', help_text='Enum field used by the Kanban board (blank disables Kanban).', max_length=64),
        ),
    ]
