# Generated by Django 5.2.17 on 2026-09-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_customentity_status_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicLogic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('field_name', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('visible', 'Visible'), ('required', 'Required'), ('readonly', 'Read-only')], max_length=20)),
                ('condition', models.JSONField(default=dict, help_text='Condition tree, e.g. {"type": "equals", "attribute": "status", "value": "Open"}. Group nodes: {"type": "and", "value": [node, node]}, {"type": "or", "value": [node, node]}, {"type": "not", "value": node}. Operators: equals, notEquals, isTrue, isFalse, isEmpty, isNotEmpty, contains, notContains, startsWith, endsWith, matches (regex), has, notHas, in, notIn, greaterThan, lessThan, greaterThanOrEquals, lessThanOrEquals, isToday, inFuture, inPast.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'dynamic logic rules',
                'ordering': ['entity_type', 'field_name', 'action', 'id'],
            },
        ),
    ]
