# Generated by Django 5.2.17 on 2026-09-12 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_dynamiclogic'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='auto_follow_entity_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='StarSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'entity_type'], name='core_starsu_user_id_661128_idx')],
                'unique_together': {('user', 'entity_type', 'entity_id')},
            },
        ),
        migrations.CreateModel(
            name='StreamSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='core_stream_entity__a1c4cc_idx'), models.Index(fields=['user', 'entity_type'], name='core_stream_user_id_345a21_idx')],
            },
        ),
    ]
