# Generated by Django 5.2.17 on 2026-09-12 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_preferences_auto_follow_entity_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('group', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'indexes': [models.Index(fields=['user', 'entity_type', 'group', 'order'], name='core_kanban_user_id_b2d5a0_idx')],
                'unique_together': {('user', 'entity_type', 'entity_id')},
            },
        ),
    ]
