# Generated by Django 5.2.17 on 2026-09-15 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_appsecret'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('record_id', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('waiting', 'Waiting'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='running', max_length=20)),
                ('cursor', models.PositiveIntegerField(default=0)),
                ('program', models.JSONField(blank=True, default=list)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('execute_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('wait_deadline', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.workflow')),
            ],
            options={
                'verbose_name_plural': 'workflow runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
