# Generated by Django 5.2.17 on 2026-09-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_workflowrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamiclogic',
            name='condition',
            field=models.JSONField(default=dict, help_text="Condition tree over this record's field values; the editor lists the available fields and operators."),
        ),
        migrations.AlterField(
            model_name='formula',
            name='script',
            field=models.TextField(help_text="One statement per line: `probability = 50`, `custom.score = 10`, `notify('Deal updated')` or `update('stage', 'Proposal')`."),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='actions',
            field=models.JSONField(blank=True, default=list, help_text='Workflow steps: immediate actions, waits or branches.'),
        ),
    ]
