# Generated by Django 5.2.17 on 2026-09-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_dynamiclogic_condition_alter_formula_script_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='trace',
            field=models.JSONField(blank=True, default=list, help_text='Compiled step indices the run has executed.'),
        ),
    ]
