# Generated by Django 5.2.17 on 2026-09-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_workflowrun_trace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='dashboard_layout',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='preset_filters',
        ),
        migrations.RemoveField(
            model_name='role',
            name='value_permissions',
        ),
    ]
