# Generated by Django 5.2.17 on 2026-09-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='recurrence_rule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='call',
            name='recurrence_uid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='historicalcall',
            name='recurrence_rule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='historicalcall',
            name='recurrence_uid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='historicalmeeting',
            name='recurrence_rule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='historicalmeeting',
            name='recurrence_uid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recurrence_rule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recurrence_uid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36),
        ),
    ]
