# Generated by Django 5.2.17 on 2026-09-11 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_call_recurrence_rule_call_recurrence_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='campaignlogrecord',
            name='bounced_type',
            field=models.CharField(blank=True, choices=[('Hard', 'Hard'), ('Soft', 'Soft')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalcampaign',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='opt_in_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='opt_in_confirmed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalopportunity',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.campaign'),
        ),
        migrations.AddField(
            model_name='lead',
            name='opt_in_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='opt_in_confirmed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='leadcapture',
            name='opt_in_confirmation',
            field=models.BooleanField(default=False, help_text='Require email confirmation before storing the lead.'),
        ),
        migrations.AddField(
            model_name='leadcapture',
            name='opt_in_lifetime_hours',
            field=models.PositiveIntegerField(default=48),
        ),
        migrations.AddField(
            model_name='leadcapture',
            name='opt_in_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_captures', to='crm.emailtemplate'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='crm.campaign'),
        ),
    ]
