# Generated by Django 5.2.17 on 2026-09-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_campaign_revenue_campaignlogrecord_bounced_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='design',
            field=models.JSONField(blank=True, help_text='Visual designer project data (used to reopen the editor).', null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(help_text='Rendered HTML. Django template syntax is supported, e.g. {{ name }} or {{ record.name }}; the visual designer writes to this field.'),
        ),
    ]
