# Generated by Django 5.2.17 on 2026-09-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_emailtemplate_design_alter_emailtemplate_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='source',
            field=models.TextField(blank=True, help_text='Authored template code. Django template syntax is supported, e.g. {{ name }} or {{ record.name }}; MJML source is compiled to responsive HTML when the source format is MJML.'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='source_format',
            field=models.CharField(choices=[('mjml', 'MJML'), ('html', 'HTML')], default='html', help_text='Format of the authored source code.', max_length=8),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(help_text='Compiled HTML. Django template syntax is supported, e.g. {{ name }} or {{ record.name }}; the visual designer writes to this field.'),
        ),
    ]
