# Generated by Django 5.2.17 on 2026-09-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_backfill_emailtemplate_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(blank=True, default='Olá {{ name }}, escreva aqui a sua mensagem. Você pode usar {{ company_name }} e outras variáveis da lista de merge tags.', help_text='Compiled HTML. Django template syntax is supported, e.g. {{ name }} or {{ record.name }}; the visual designer writes to this field.'),
        ),
    ]
