# Generated by Django 5.2.17 on 2026-09-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_emailtemplate_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='design',
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(blank=True, help_text='Compiled HTML cache derived from the source.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='source',
            field=models.TextField(blank=True, default='<mjml>\n  <mj-head>\n    <mj-title>{{ company_name }}</mj-title>\n    <mj-preview>News from {{ company_name }}</mj-preview>\n    <mj-attributes>\n      <mj-text font-family="Helvetica, Arial, sans-serif" font-size="15px" color="#374151" line-height="1.6" />\n      <mj-button font-family="Helvetica, Arial, sans-serif" background-color="#4f46e5" color="#ffffff" border-radius="6px" />\n    </mj-attributes>\n  </mj-head>\n  <mj-body background-color="#f3f4f6">\n    <mj-section background-color="#ffffff" padding="24px">\n      <mj-column>\n        <mj-text align="center" font-size="20px" font-weight="bold" color="#111827">\n          {{ company_name }}\n        </mj-text>\n      </mj-column>\n    </mj-section>\n    <mj-section background-color="#ffffff" padding="24px">\n      <mj-column>\n        <mj-text>Hello {{ name }},</mj-text>\n        <mj-text>\n          Start writing your message here. Replace this text with your content.\n        </mj-text>\n      </mj-column>\n    </mj-section>\n    <mj-raw>\n      <div style="padding: 16px; text-align: center; font-size: 12px; color: #9ca3af;">\n        &copy; {{ company_name }}. All rights reserved.\n      </div>\n    </mj-raw>\n  </mj-body>\n</mjml>\n', help_text='Authored template code and source of truth. Django template syntax is supported, e.g. {{ name }} or {{ record.name }}; MJML source is compiled to the responsive HTML stored in body.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='source_format',
            field=models.CharField(choices=[('mjml', 'MJML'), ('html', 'HTML')], default='mjml', help_text='Format of the authored source code.', max_length=8),
        ),
    ]
