# Generated by Django 5.2.17 on 2026-09-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_remove_emailtemplate_design_alter_emailtemplate_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcapture',
            name='form_captcha',
            field=models.BooleanField(default=False, help_text='Require a captcha token on submissions (needs a configured captcha provider).'),
        ),
    ]
