# Generated by Django 5.2.17 on 2026-09-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_leadcapture_form_captcha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcapture',
            name='field_list',
            field=models.JSONField(blank=True, default=list, help_text='Allowed form fields; leave empty to use the defaults.'),
        ),
    ]
